# Generated by Django 5.2.5 on 2025-09-01 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subcategory',
            field=models.ManyToManyField(related_name='subcategory', to='core.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='core.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='objectives', to='core.objectives'),
        ),
    ]
