# Generated by Django 5.2.5 on 2025-09-01 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_objectives_alter_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='objectives',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subcategory',
            field=models.ManyToManyField(related_name='courses', to='core.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='core.category'),
        ),
        migrations.DeleteModel(
            name='Objectives',
        ),
        migrations.AddField(
            model_name='course',
            name='objectives',
            field=models.JSONField(default=list),
        ),
    ]
