# Generated by Django 5.2.5 on 2025-09-02 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('file', 'File')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('order', models.PositiveIntegerField()),
                ('is_preview', models.BooleanField(default=False)),
                ('content', models.TextField(help_text='Video path, article content, or file path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
