# Generated by Django 5.2.5 on 2025-09-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_section_order_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/files/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
