# Generated by Django 5.2.5 on 2025-09-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lecture_article_lecture_file_lecture_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='content',
        ),
    ]
